collections:
  posts:
    author: 'Author Name' # Default author, if not provided in a post
    sort: '-date'
    path: 'blog/{filename}'
  categories:
    path: '/blog/categories/{filename}'
    posts: |
      function ($page, $allPosts) {
          return $allPosts->filter(function ($post) use ($page) {
              return $post->categories ? in_array($page->getFilename(), $post->categories, true) : false;
          });
      }